### ISSUE TITLE
Develop guidelines for contributing and ongoing changes and approval

### ISSUE THREAD

**Issue by NorahMaki** [18F/ux-guide#114]
-Schedule call with Dahianna (and Star?)
- Is there a way to define what types of changes need review?

**Comment by NorahMaki** [comment]
Notes from 2/21 discussion
- In the past, didn't have process for PRs, this will be new process for us, to make sure there is alignment at GSA
- Tag Dahianna as a reviewer for any PRs
- Dahianna will take a look - small edits can be reviewed by her and Anne
- If more significant changes, she will take it to Star to escalate as needed for approval
- May need to update review process as we go along, since it's a new process

**Comment by MelissaBraxton** [comment]
We met with Dahianna and she said that process for reviewing any changes following initial publication will vary on a case by case basis. At a min., we need to update our contributing guide to instruct folks to loop outreach in when they create PRs or new issues. 

Acceptance criteria
- [ ] We have documented the need to loop TTS outreach in on any proposed content changes in our repo.

Tasks
- [ ] Update contributing guide to include TTS outreach in approval process
- [ ] Update issue template to tag Dahianna

Definition of done
- [ ] Meets acceptance criteria
