### ISSUE TITLE
Footer guidance

### ISSUE THREAD

**Issue by cmajel** [18F/ux-guide#158]
**Background**
Follow up from chat with @MelissaBraxton last week. In the branding guidelines for new sites, GSA asks that footers include a link back to GSA. Here's a design and language that Dahianna and I recommend. 

![footer-structure](https://user-images.githubusercontent.com/2374206/78823162-39d6c880-79aa-11ea-9164-645abae4be94.jpg)

A few notes:
* If you have footer links, you can include the top grey section - feel free to remove if it's not needed.
* The GSA logo should link back to the [GSA homepage](https://www.gsa.gov/), and the TTS link should link to [TTS's page](https://www.gsa.gov/about-us/organization/federal-acquisition-service/technology-transformation-services).
* Suggested language: "The UX guide is a project of GSA’s Technology Transformation Services, and maintained by 18F", with a link back to [18F's site](https://18f.gsa.gov/). 

**Acceptance criteria** 
- [ ] 
- [ ] 

**Tasks**
- [ ] 
- [ ] 

**Definition of done**
- [ ]  One of the POs has approved the change
- [ ]  Outreach approval (if needed)

**Comment by nickttng** [comment]
👋@cmajel Is this ready to be built and implemented? If so, are you interested in taking on this task? If not, no worries. I can take this on.

**Comment by cmajel** [comment]
👋 hi @nickttng I've build a demo version of this based on digital.gov's original components over here:
https://github.com/cmajel/federalist-uswds-jekyll 

There are some more details about where this comes from in this issue:
https://github.com/18F/brand/issues/211

I reviewed it today with @Dahianna, and you're good to move forward with the following language in the `org-copy`:

> The UX Guide is a product of GSA’s Technology Transformation Services, and managed by 18F.

Let us know if questions come up! Feedback on the code and component is also much appreciated ❤️

**Comment by cmajel** [comment]
A heads up that I've updated [the guide template](https://github.com/cmajel/federalist-uswds-jekyll) with a full footer demo. It includes the accordion of `required links` that was a part of the draft anchor component recommendation - we are still verifying if these are the links we should include. 

I'd recommend including at least the GSA logo and the language to the right with attribution and link backs to TTS and 18F for an MVP.

<img width="1440" alt="anchor--1 closed" src="https://user-images.githubusercontent.com/2374206/81418636-f8594a80-911a-11ea-95b5-985d025afcb8.png">
<img width="1440" alt="anchor--2 opened" src="https://user-images.githubusercontent.com/2374206/81418638-f8f1e100-911a-11ea-80fb-d3c8d17f3dfd.png">
