### ISSUE TITLE
Preview link in README doesn't display styles

### ISSUE THREAD

**Issue by maya** [18F/ux-guide#186]
The "preview the site on Federalist" link in the README doesn't display styles:
https://federalist-48b3228b-0241-4802-9442-e08ff5c3e680.app.cloud.gov/site/18f/ux-guide/

Maybe there's another link?

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.

**Comment by bpdesigns** [comment]
@mgwalker is this relevant once we move to Pages?

**Comment by mgwalker** [comment]
Proposal: we remove that link from the README entirely. Preview links are different for each branch. A static link will never be up-to-date.

**Comment by bpdesigns** [comment]
@mgwalker sounds good to me.
