### ISSUE TITLE
Update 'Under development' content in README.md

### ISSUE THREAD

**Issue by nickttng** [18F/ux-guide#215]
**Is your feature request related to a problem? Please describe.**
In the README.md, the `Under development` (See content below) could be updated to reflect that the UX Guide is no longer under development, which has been publicly launched, so that users are not under impression that it is still under development

> Under development
> This guide is currently under development. It is a living guide that will continue to be added to and updated over time. You can review our goals, preview the site on Federalist, contribute or get a general overview below.

**Describe the change you'd like to see**
Perhaps reusing this line from the announcement blog post or in a similar spirit stating that it is a living guide

> In the spirit of iterative design, we don’t expect that this guide will ever be “done”—it’s a living thing that we’ll keep improving using your feedback, so send us your ideas! 

**Describe alternatives you've considered**

An alternative could be simply omitting few words from the original line that implies 'under development'

> It is a living guide that will continue to be added to and updated over time. You can review our goals, contribute or get a general overview below.

**Reviewers** 
@vishaliyer-18f (Acting PO) or future POs to review and consider if this is an issue to solve or not

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
