### ISSUE TITLE
As a non-GSA visitor, I need to be able to recognize links to which I can't get access

### ISSUE THREAD

**Issue by jstrothman** [18F/ux-guide#225]
**Background**
The UX Guide shows a padlock after links to Google docs which are only accessible to GSA & TTS Slack links, etc. We get doc access requests an average of 3 times/week from people w/non-gov email addresses who have clicked on the Google 'Request access' button after following the link from the Guide. 
When we implemented the padlock icon next to Google links, we removed explicit wording.

We could add a tooltip, explicit text, or something else to make it clearer that these links are GSA-only.
We also need to address the repeated link text on the page, i.e. 'Gdoc' for all of the GSA-only links on the Resources page. This is a problem for people listening to the page with a screenreader who hear the same link over-and-over and must guess whether this is a repeat of the previous link they heard. 

See [screenshots and notes in Mural](https://app.mural.co/t/gsa6/m/gsa6/1609260386260/1b5d2018d2dff01af678d7fbfbab5eeccd1182ef)

**Acceptance criteria** 
- [x] update "About" and "Do" pages for PO review with new wording - "(18F/GSA internal use only)" and "18F/GSA internal version)" where applicable 
- [x] update all pages with new wording 

**Definition of done**
- [x]  One of the POs has approved the change

**Comment by ryanhofdotgov** [comment]
Hi – just wanted to connect this issue with our recent conversation about the title attribute [that 18F/private-eye sets](https://github.com/18F/private-eye/blob/eb472945081ef4613903bb40fd5fa463543891f7/private-eye.js#L92). It was removed in this guide's copy of the private-eye JavaScript in [this commit](https://github.com/18F/ux-guide/pull/176/commits/86abb186a6536a47445f1d091bd7f13fa4bc9dcf) – restoring those lines will add back the tool tip.

Of course, the title attribute/tool-tip approach will still have all the problems listed in that article you shared with me: [Using the HTML title attribute](https://developer.paciellogroup.com/blog/2010/11/using-the-html-title-attribute/)

**Comment by jstrothman** [comment]
Thank you @ryanhofdotgov -- it's true we removed the title attribute, and I'm not sure we have a readily-available accessible tooltip alternative.

**Comment by bpdesigns** [comment]
Talking with former product owner of the ux guide in the alumni slack - "There was no rhyme or reason to making them part of the repo vs part of the wiki, outside of making them available to anyone who forks the repo."

**Comment by bpdesigns** [comment]
@jstrothman I went with changing the language directly in the file. My rationale being its easier for 18F folks to find as they read. If we move the files to the bottom of the page it might take more time to cross-reference)

**Comment by jstrothman** [comment]
For future reference:
We opted to address this by changing the link text of GSA-only Drive files from `Gdoc` to `18F/GSA access only`

For screen reader users listening to a list of links, they will hear a descriptive link followed by the next link's text: `18F/GSA access only`. This repetitive text for different targets is allowable per [WCAG explanation of 2.4.4 example re different versions of book links](https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html#examples).

**Comment by jstrothman** [comment]
@bpdesigns I think this issue can be closed--what do you think?

**Comment by bpdesigns** [comment]
I agree.
