### ISSUE TITLE
Some pages linked from search.gov results have no content

### ISSUE THREAD

**Issue by jstrothman** [18F/ux-guide#245]
**Background**
A bunch of searches on the UX Guide and TTS Handbook (and any other of our sites that use search.gov and include the UX Guide's content) link to empty pages on the Guide. For example:
1. Search for 'interview' from https://handbook.tts.gsa.gov/ or https://ux-guide.18f.gov/
2. Click on result for Interview Debrief Guide or Interview Guide
Result -> Page with the UX Guide's header, empty body, and footer, followed by the title of the page repeated twice (see screenshot in [related Handbook issue #2198](https://github.com/18F/handbook/issues/2198) 

Many of the site's resources are markdown pages which include a `permalink` in the page's metadata, e.g.
https://github.com/18F/ux-guide/blob/master/_pages/resources/interview-guide.md
has a permalink `/interview-script/`. Perhaps that is resulting in the empty page?

**Acceptance criteria** 
- [ ] Empty pages redirect to the intended markdown page so that existing links are not broken

**Tasks**
- [ ] 
- [ ] 

**Definition of done**
- [ ]  One of the POs has approved the change

**Comment by brentryanjohnson** [comment]
Looks like this was an issue with the deprecated front matter layout value. A change from `layout: page` to `layout: post` will fix the rendering issue, but a redirect to the GitHub markdown file sounds like the preferred interim option. :)

**Comment by jstrothman** [comment]
In discussion w/ @brentryanjohnson we agreed the UX group should talk about how we understand these pages to be used and make a decision for format / location based on that (e.g. if goal is copying the text for editing, or saving a pdf, perhaps a layout with no left nav to hint at ease of printing, and a breadcrumb to get back to the Resources page).

In the meantime, options:
1. Change `layout: page` to `layout: post` (as mentioned abov), but this means removing the h1 which is repeated from the front matter when rendered in the post layout. If we removed it, then when it is viewed in GitHub, it won't have an h1.
2. Remove layout altogether (this results in losing the lock icon added by privateye.js)
3. Set redirects in these resource pages

Going with #3: redirects as temporizing fix until UX team can decide on best solution.
