### ISSUE TITLE
Change branch name from master to main

### ISSUE THREAD

**Issue by jstrothman** [18F/ux-guide#247]
**Background**
Let's remove the slavery-related language of `master` for our deployment branch and change it to `main`

**Acceptance criteria** 
- [x] We have an active `main` branch and no `master` branch in the methods repo
- [x] Federalist has the live site branch set to 'main'

**Definition of done**
- [x]  One of the POs has approved the change

**Comment by cannandev** [comment]
Approved by Ben Peterson @bpdesigns
