### ISSUE TITLE
Update compensation information to reflect equity-centered practice

### ISSUE THREAD

**Issue by jstrothman** [18F/ux-guide#252]
**Background**
The UX Guide includes information on the process for compensating participants, but it could be more helpful with regard to process and providing value back to the participant. Also see #126 re recruiting diverse participants.

- Change all instances of `incentives` to `compensation` (gov can't pay incentives)
- Remove as many references to `user testing` as possible, such as with `user research` and/or `participation in design research`
- Explain that approved process is that we can't pay participants directly, so initial OGC guidance is to work with a recruiting agency, however this is not ideal: we'll be more successful at achieving diverse and representative participation if we work with trusted community organizations, including from tribal nations.
- Give examples of ways user research directly advances mission
- Should we retain the link to `collecting value statements`? This form was created by CoE as described in [this doc](https://docs.google.com/document/d/1oWDxVUsRbO1ELNmni3Qa-uYPhXDWuNM3HESgAUxs7Uw/edit). Can we find out who owns this doc and whether they have examples, and are still monitoring for responses?
- Offer thoughts about what we're compensating for (not just time of session, but also can be travel time if have to be away from work, transportation, expertise of related experience not necessarily just based on their career compensation as is often the case with 3rd party recruiters)
- Offer examples of ways beyond financial compensation that we can provide value back to participants (information to them and/or their community, continued input, updates on changes)
- Change gdoc link for authorization doc to [18F's copy](https://docs.google.com/document/d/1ehb3W14_eEo8DdHjU0bCeyzG_t8I__7VyLV_cU4ZmQY/edit) (which refers to user research, not testing) 

**Acceptance criteria** 
- [x] Page addresses list above
- [x] Site no longer uses the word `incentive`

**Definition of done**
- [ ]  One of the POs has approved the change

**Comment by bpdesigns** [comment]
I'm going to remove the piece about value statements for now. I messaged the #wg-user-research-compensation a few weeks ago while looking into this for login and got crickets. I think this was an idea with no active owner.

**Comment by bpdesigns** [comment]
closing this issue. Issue is covered by #271
