### ISSUE TITLE
Link to example recruiting materials from the Plan article. 

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/ux-guide#27]
In the participants and recruiting section, either include or link to examples of recruiting materials, such as the social media intercept examples that are included the Legal section: 

https://docs.google.com/a/gsa.gov/document/d/13FWBP5wMf_MgDToVBBrkOafFe5T8NsldzttGENhGgSU/edit?disco=AAAACsPQo7M

**Comment by lauraponce** [comment]
I feel like it's worth expanding this issue a bit more. The current `Participants and recruiting` section of the Guide really only discusses two things: `identifying target groups` and `defining recruitment criteria`, but it doesn't say anything about how we go about doing the actual recruiting. 

@jstrothman what do you think about broadening the scope of this to focus on adding a third subsection to `Participants and recruiting` that covers the "reaching out to people" part of recruiting and could include examples such as the intercept ones from the `Legal` section?
