### ISSUE TITLE
Add example types to user compensation value statements description

### ISSUE THREAD

**Issue by jstrothman** [18F/ux-guide#271]
**Background**
The Guide's Plan page describes how we compensate participants. In September 2021, we were able to successfully provide [examples of when not compensating participants blocked user research](https://docs.google.com/document/d/1RzPgj_E3VdoJZKZNmxU-LIwUc4cYiVkQDMvP92MUIjc/edit?usp=sharing) 

**Acceptance criteria** 
- [ ] https://ux-guide.18f.gov/research/plan/#financial-compensation now includes a description of the information needed in examples and a link to the [google doc with examples](https://docs.google.com/document/d/1RzPgj_E3VdoJZKZNmxU-LIwUc4cYiVkQDMvP92MUIjc/edit?usp=sharing)

**Definition of done**
- [ ]  One of the POs has approved the change

**Comment by bpdesigns** [comment]
@jstrothman Does this issue supersede #252? 

@bpdesigns to confirm that the compensation working group intends for compensation content to live in the ux guide and link to TTS Handbook or if its the other way around

**Comment by jstrothman** [comment]
> @jstrothman Does this issue supersede #252?

@bpdesigns I'd say yes

**Comment by bpdesigns** [comment]
Thank you @jstrothman

**Comment by bpdesigns** [comment]
The research compensation process will live in the TTS Handbook. Closing this issue and will create a new one to point readers to the TTS handbook for the compensation process so there is one source or truth for this process and if it changes only one place will need to be updated.
