### ISSUE TITLE
Unable to view Design System in UX Guide, redirects to 404 Page

### ISSUE THREAD

**Issue by n-brock** [18F/ux-guide#284]
**Is your feature request related to a problem? Please describe.**
When I view the UX Guide and contents, I am unable to view the Design System, it redirects to a 404 Error Page.

**Describe the change you'd like to see**
Option 1 - Ensure all hyperlinks go to designated screen/page assigned
Option 2 - Include all material in the Github Repo for this particular instance of the UX Guide and limit redirecting users away from GitHub and this specific repo - 18F UX Guide

**Describe alternatives you've considered**
Refer to Option 1 above - "Ensure all hyperlinks go to designated screen/page assigned"

**Additional context**
<img width="1440" alt="Screen Shot 2022-07-07 at 9 59 48 AM" src="https://user-images.githubusercontent.com/3265381/177794040-d58d98c9-23db-4f66-9e12-055d70889e07.png">
<img width="1440" alt="Screen Shot 2022-07-07 at 9 59 48 AM" src="https://user-images.githubusercontent.com/3265381/177794040-d58d98c9-23db-4f66-9e12-055d70889e07.png">
<img width="1440" alt="Screen Shot 2022-07-07 at 9 59 48 AM" src="https://user-images.githubusercontent.com/3265381/177794040-d58d98c9-23db-4f66-9e12-055d70889e07.png">

**Add reviewers** 
@dahianna

When you submit your issue, add @dahianna in tts-outreach as a reviewer.

**Comment by annepetersen** [comment]
Hi there, and thanks for submitting this! 

I'm having trouble replicating this issue. I assume you're clicking on the "use design systems" link within the Design section of [How to use this guide](https://ux-guide.18f.gov/#how-to-use-this-guide), which goes to [Use a design system](https://ux-guide.18f.gov/design/use-a-design-system/). When I click that link, it does not 404 for me. 

Is it a different link you're trying to use? Am I wrong about how you tried this? Happy to help if I can figure out what to fix.

**Comment by echappen** [comment]
Because we switched our main branch's name from `master` to `main`, any hyperlinks to Github pages with `/master/` in them will 404. I can work on updating these links.

**Comment by bpdesigns** [comment]
Thanks @echappen! + good to know the root of the issue :)
