### ISSUE TITLE
Publish all pages on ux-guide.18f.gov instead of linking some pages to GitHub

### ISSUE THREAD

**Issue by mgwalker** [18F/ux-guide#300]
The following pages redirect to GitHub:

- assisting-in-research
- interview-checklist
- interview-debrief-guide
- interview-guide
- participant-agreement-spanish
- participant-agreement
- privacy-act-notice
- research-alignment-workshop
- research-lead
- research-plan
- usability-test-guide
- researcher-introduces-themselves
- researcher-sends-agreement
- stakeholder-introduces-researcher

They all redirect to themselves, just on GitHub instead of in the guide. ~I haven't yet looked to check how these pages are referenced from within the guide, but my guess is this could all be done as one fairly simple piece of work. I will check on the links and report back here in a little bit.~ Updating the links to these pages is also straightforward.

**Comment by MelissaBraxton** [comment]
@mgwalker - You want to take a crack at refining this one? Seems like a good thing to maybe pick up in the near term, if you're on a role following #298!

**Comment by mgwalker** [comment]
Yes! I meant to come back and put a description and more info in yesterday, but I completely forgot... the project board makes it super easy to create empty issues and forget about the details. 😂
