### ISSUE TITLE
Research and implement a way to sync labels between github projects

### ISSUE THREAD

**Issue by bpdesigns** [18F/ux-guide#304]
this could be useful for Adventures in Co-working right now and in the future if we pull in in other repos to the project board.

**Comment by mgwalker** [comment]
Possibly a daily run of this action, using one of the repos as a label-source-of-truth? https://github.com/marketplace/actions/label-sync

**Comment by bpdesigns** [comment]
Option to delete labels that are not source or truth. We should disable this. 

Done: add labels from one source of truth to the other site so there is consistency in the board.

**Comment by mgwalker** [comment]
Here is what would happen if we sync from Methods to UX-Guide right now. These labels would get added to UX-Guide:

- accessibility
- design/styling
- IDEA/Mandated modernization req
- Needs refinement
- new method
- print
- sand box
- security
- user story
- visual design
- won't fix
- work in progress

I propose that we remove the `work in progress` label, as the board should be how we know what's in progress and what isn't.

I also propose that we rename `IDEA/Mandated modernization req` to something more like `site requirement` (like what's already in UX-Guide) or `mandated` for brevity.

And I wonder if `design/styling` and `visual design` are the same.

---

Separately, there are some labels in UX-Guide that are not in Methods that I would propose we remove:

- done
- status - do not merge
- status - ready for review

Similar to `work in progress`, these statuses should be reflected by the board, I think. That is a separate question from this issue, but I wanted to write my thoughts down somewhere and this seemed as relevant a place as any. 😛

**Comment by bpdesigns** [comment]
Thanks @mgwalker that makes sense to me

**Comment by mgwalker** [comment]
closed by #307
