### ISSUE TITLE
Fix incorrect and broken links in the UX guide

### ISSUE THREAD

**Issue by mgwalker** [18F/ux-guide#306]
There are two links in the UX guide that are straight-up broken:
* https://ux-guide.18f.gov/research/lead/
  Has a link to http://adaptivepath.org/uploads/documents/apr-007_taskbased.pdf, but that link is no longer valid. adaptivepath.org seems to be a defunct domain
* https://ux-guide.18f.gov/research/plan/
  Has a link to https://ux-guide.18f.gov/our-approach/values-and-principles/#we-train-advocates. The page exists, but the `we-train-advocates` header does not. Maybe it's supposed to be the `we-coach-advocates` header?

<details>
<summary><strong>The comments collapsed below are no longer applicable. See <a href="#issuecomment-1351643248">this comment below</a> for more information.</strong></summary>
  
Most pages also have an error where there is an anchor tag with an empty `href` attribute. These are the all inherited from the site header, where it is intended to populate "secondary" navigation links (I don't know what that means). There aren't any secondary links in the navigation data so it *shouldn't* be writing anything at all, but it does, and because there aren't any links, it's all just empty. The empty anchor tag is a problem.

The quick fix to the header issue would be to take out the part of the header template that renders secondary navigation links. That seems okay since there aren't any, but that header is (I think) copied from a USWDS template, so maintainers in the future might expect secondary links to just work and this customization might cause some confusion. The more robust fix would be to figure out why it's trying to render secondary links that don't exist, but having stared at it for a few minutes, I'm already thoroughly perplexed.
</details>

**Comment by echappen** [comment]
Regarding the empty links in the header: would it be okay for the CI/CD step in #305 to bypass this issue by ignoring empty links? It seems the step's main purposes are to correct human error when adding URLS and to catch newly outdated URLS. Although possible, it seems rather unlikely that a person would add a totally empty link. So I'm wondering if the step could be more forgiving on the outset to these edge cases.

**Comment by mgwalker** [comment]
That makes sense! Let me see if html-proofer supports turning that off, and then we can make a note in the issue to fix the header that this check should eventually be turned back on (IMO) because it suggests a problem somewhere. It might also be an accessibility issue, though if the `href` is empty, it shouldn't be in the tabbing order at all.

**Comment by mgwalker** [comment]
Okay, updated #305 to allow the empty hrefs for now. I do think it should eventually be added back, but getting us closer to passing tests from our starting point makes sense to me.

**Comment by MelissaBraxton** [comment]
This can also be addressed as a first task under #568.

**Comment by lauraGgit** [comment]
the outside link may be addressed in https://github.com/18F/ux-guide/pull/328
