### ISSUE TITLE
Update content that informs how Bias impacts design research

### ISSUE THREAD

**Issue by bpdesigns** [18F/ux-guide#401]
**Describe the change you'd like to see**
Update content that informs how Bias impacts design research

**Additional context**
Related to issue #310 
Draft [doc](https://docs.google.com/document/d/1yY0TvT_7qfArXZBfjkWZygrhjXO-N1Vp3PVYj27nCao/edit#)

**Tasks**
- [x] Review and update content on the Bias page 

**Outcomes**
- [x] Updated content on the Bias page 

**Add reviewers** 
TBD

**Comment by bpdesigns** [comment]
@austinhernandez FYI

**Comment by MelissaBraxton** [comment]
@egamble23  - Can help out with content editing and plain language review

**Comment by MelissaBraxton** [comment]
@austinhernandez  - I think this is in progress? Are you on track to wrap it up by Tuesday, 6/6?

**Comment by austinhernandez** [comment]
It is in progress. On track to wrap up and present at the demo
