### ISSUE TITLE
Investigate publication process for rolling publication.

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/ux-guide#43]

**Comment by NorahMaki** [comment]
To learn:
- What should be public/private and where they live respectively 
- When/how we push changes to Federalist

**Comment by MelissaBraxton** [comment]
If Federalist is set up to deploy from our master branch, then the site will update automatically as new code is pushed to master. I had to request access to Federalist, and I need to wait for it to be approved in order to double check. 

Right now the repo is public, and we can progressively fix page links that were broken to take down previews.

**Comment by MelissaBraxton** [comment]
Review and publication pipeline
1. Director reviews
2. UX guide team addresses Director feedback
3. Writing lab reviews
5. Outreach reviews
6. Angela signs off
7. Make changes in GitHub directly
8. Merge to Master
9. Un-break preview perma links
10. site builds in Federalist automatically

**Comment by MelissaBraxton** [comment]
Article priority order
1. About this guide
2. Our approach 1.1-1.2
3. Our approach 1.3-1.4
4. Research 2.1-2.4
5. Research 2.5-2.8
6. Design
