### ISSUE TITLE
Publish Part 2 of the Guide

### ISSUE THREAD

**Issue by NorahMaki** [18F/ux-guide#62]
Pending Outreach and Director approval

**Comment by MelissaBraxton** [comment]
Background
We have approval from the design chapter and team to publish this article.

Acceptance criteria

- [X]   Outreach has reviewed and approved content
- [ ]   Article is publicly available

Tasks

- [X]   Create writing lab issue for this article
- [X]   Have outreach review and approve Google doc
- [X]   Have Angela review and approve Google doc.
- [ ]   Identify opportunities to link with Method Cards
- [X]   Update GitHub to reflect approved content in Google doc
- [ ]   Make the content public
- [ ]   Announce the publication in Slack

Definition of done

- [ ]   One of the POs has approved the change
- [X]   Outreach approval (if needed)

**Comment by MelissaBraxton** [comment]
Closing as we will publish and announce all sections of the guide at the same time.
